error: silence ETIMEDOUT and EHOSTUNREACH errors
There's nothing we can do about these errors due to
network failures and bad clients, either, so do not spew
a backtrace for them.